### ISSUE TITLE
Publish new DIAG website

### ISSUE THREAD

**Issue by wouterbulten** [DIAGNijmegen/website-content#250]
The current items have to be resolved before we can deploy the new diag website:

- [x] Disable Calendar on home page
- [x] Disable Twitter on home page
- [x] Convert former employee page to a manually curated list (#191 #210)
- [x] New "Research" page with subpages for Research lines (replaces projects) (#226)
- [x] Move old highlights from diagnijmegen.nl to the new site (#234)
- [x] Publications per year on separate pages (#244)
- [x] Create redirects for all old pages of diagnijmegen.nl (#188)
- [ ] PDF Download support for new website (#173)
- [ ] Check which content we still need to move from the old website to the new (#239)
- [x] Highlights to news (#258)

**Comment by bramvanginneken** [comment]
#173 does not have to be fixed prior to deploy unless deploy breaks the old pipeline

**Comment by bramvanginneken** [comment]
fixed former employee page, added haimashree is complete now

**Comment by bramvanginneken** [comment]
I have copied all old highlights to my computer, I will add the most interesting ones as old news items #234

**Comment by sjoerdk** [comment]
> #173 does not have to be fixed prior to deploy unless deploy breaks the old pipeline

I would imagine #173 does need to be fixed.  Firstly because the pdfs that can be downloaded via the old pipeline are coming from the old literature SVN repo, which you probably want to stop using. Secondly because the random keys in the download links in the old pipeline are coming from a custom database on rdwww. On the old websites this db can accessed via PHP, but the pelican website cannot use this I think.

**Comment by wouterbulten** [comment]
@sjoerdk we have a workaround for this by sending a request to the old service to fetch the PDF. It's not the nicest solution, but it works for now. See https://github.com/DIAGNijmegen/website-content/blob/master/radboudumc-template/templates/publication.html#L61

Ideally we would launch the new pdf service together with the new website, but this depends on how fast we can deploy the service.

**Comment by sjoerdk** [comment]
Haha interesting!
So the workaround wraps around the old pdf download mechanism completely. But the email that is sent to the user will still offer a download of a PDF that is on rdwww in the literature SVN right? And you plan to put diag.bib in a github repo instead right? So how will you sync the PDFs between this new github repo and the literature SVN?

**Comment by wouterbulten** [comment]
The plan is to deploy the new PDF system, before the sync between git and svn is stopped.

**Comment by sjoerdk** [comment]
Oh I did not know about any sync between git and svn. Thanks for the info. If this is synced than it's fine. Who's responsible for this syncing? And is it done on rdwww itself? or somewhere else?

**Comment by wouterbulten** [comment]
@cjacobs1 created the sync if I'm correct. I'm not sure where it runs.

**Comment by sjoerdk** [comment]
@cjacobs1, Do you know whether this syncing still runs? And how? I could not find this on rdwww:/home/literature

**Comment by cjacobs1** [comment]
> @cjacobs1, Do you know whether this syncing still runs? And how? I could not find this on rdwww:/home/literature

Yes, this still runs. It runs as a docker container in a VM on HADINGUS.

> There is currently an issue that I can't pinpoint: A user emailed me that some recent pdf download links do not work. I've made a trac ticket: https://repos.diagnijmegen.nl/trac/ticket/9365 Could @cjacobs or @MeykeHermsen (as literature pipeline person) have a look?

Coen and I had a look. Our docker container that runs the sync script was not functioning because a disk ran full. It is fixed now. We'll respond to the ticket.

**Comment by wouterbulten** [comment]
Website is deployed.
